### PR TITLE
Updated travis.yml for all Ruby

### PR DESCRIPTION
**Pull request by ferdinandrosario**

### CODE REVIEW

**Comment by osiro** [comment]
Cheers mate!

I'll remove byebug as a development dependency, that's gonna make CI green and also make developers free to use whatever debugger tools they fell like.

**Comment by ferdinandrosario** [comment]
Thanks @osiro :smile: :+1:

**Comment by osiro** [comment]
Looks like tests are failing for Rubinius and JRuby, it looks like is something to do with OpenStruct, will have a look into that soon.

**Comment by osiro** [comment]
Done!

Enceladus now works fine with MRI, jruby and rbx.

**Comment by ferdinandrosario** [comment]
Thanks @osiro .. you are awesome... :heart: :heart:

**Comment by ferdinandrosario** [comment]
@osiro shall I change the travis for latest stable Cruby(2.1.6) and ruby-head,jruby-head under allowed-failure list in travis? I feel That will make this gem more updated one....

**Pull request merged**
